using BootCampPrep.Applying_OOP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BootCampPrep
{
    public class MonsterTypeA : IMyInterface
    {
        //autogenerated
        //public string Name { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        //public int Number { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        //public Element Type { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

        private string name;
        private int number;
        private Element type;

        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }

        public int Number
        {
            get
            {
                return number;
            }
            set
            {
                number = value;
            }
        }

        public Element Type
        {
            get
            {
                return type;
            }
            set
            {
                type = value;
            }
        }

        public string Evolve(string newName)
        {
            string toReturn = string.Format("{0} evolved into {1}!", this.Name, newName);
            OOPStuff01.ChangeName(this, newName);
            this.number += 1;
            return toReturn;
        }

        public override string ToString()
        {
            return string.Format("{0} is number {1} and type {2}.", name, number, type.ToString());
        }
    }
}
